services:
  mongo:
    container_name: mongo
    image: mongo:8.2.2
    networks:
      - mongo-compose-network
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./.database/:/data/db/
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.2
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
    networks:
      - mongo-compose-network
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"

  backend:
    container_name: backend
    build: ../backend-python/.
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ../frontend-angular:/app/frontend-angular

networks:
  mongo-compose-network:
    driver: bridge