services:
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - mongo-compose-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./.database/:/data/db/
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
    ports:
      - '8081:8081'
    volumes:
      - ./.database:/data/db

  backend:
    container_name: backend
    build: ../backend-python/.
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://admin:1234@mongo:27017/"

networks:
  mongo-compose-network:
    driver: bridge
  backend:
    driver: bridge